import type { SystemChangelogEntry } from "./changelogService";

// Master compiled GitHub deployment history covering all releases
export const COMPLETE_GITHUB_DEPLOYMENTS: SystemChangelogEntry[] = [
  {
    id: "3.8.6cv",
    version: "3.8.6cv",
    git_commit_tag: "3.8.6cv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.8.6cv - Modernize SMTP Email Templates with Dark Theme: Updated all Supabase Auth and transactional email templates with sleek dark background (#0b0f17), slate card containers, glowing cyan buttons, and high-visibility OTP verification code highlight boxes ({{ .Token }}).",
  },
  {
    id: "3.8.6bv",
    version: "3.8.6bv",
    git_commit_tag: "3.8.6bv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.8.6bv - Password Recovery Link Routing & Global Modal Interceptor: Added global PasswordRecoveryModal, updated RootGate to redirect recovery tokens directly to password update workflow, and ensured all resetPasswordForEmail dispatches include explicit redirectTo URLs.",
  },
  {
    id: "3.8.6av",
    version: "3.8.6av",
    git_commit_tag: "3.8.6av",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.8.6av - Password Change OTP Security Hotfix: Enforced strict 8-digit OTP verification via Supabase verifyOtp, rejecting modified or incorrect verification codes prior to password update, and updated input slots to 8 digits.",
  },
  {
    id: "3.8.6v",
    version: "3.8.6v",
    git_commit_tag: "3.8.6v",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.8.6v - Enhanced Account Security: Introduced 2-step password update with email OTP code confirmation, direct email verification link fallback, live password strength meter, 60s cooldown timer, and bilingual English/Tagalog support.",
  },
  {
    id: "3.8.4ev",
    version: "3.8.4ev",
    git_commit_tag: "3.8.4ev",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.8.4ev - AI Vision Scanner Dropzone Optimization: Removed redundant mobile camera button, retained prominent Upload from Gallery button, implemented interactive drag-and-drop file upload with visual feedback states, and introduced clean focus behavior that hides the upload dropzone when a photo is staged.",
  },
  {
    id: "3.8.4dv",
    version: "3.8.4dv",
    git_commit_tag: "3.8.4dv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.8.4dv - Smart Calendar Today Highlight Enhancement: Preserved 1px border thickness from simulation plan while styling the Today date cell with live emerald green background tint and border accents across Actual Tracker and Simulation Plan views.",
  },
  {
    id: "3.8.4cv",
    version: "3.8.4cv",
    git_commit_tag: "3.8.4cv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.8.4cv - Container Border Alignment: Reverted internal component border radius while maintaining header and sidebar container borders.",
  },
  {
    id: "3.8.4bv",
    version: "3.8.4bv",
    git_commit_tag: "3.8.4bv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.8.4bv - Upstream Full Synchronization & Unified Experience: Integrated Core Views UI Modernization (Smart Calendar, Analytics, Forecasting, Bill Calculator with Stack Template Zinc theme) and Header Redesign (sharp square aesthetics, room switcher in profile menu, page name before room breadcrumb) with Production Settings Hierarchy, Notification Activity Center logs feed, and dynamic contrast fixes.",
  },
  {
    id: "3.8.4av",
    version: "3.8.4av",
    git_commit_tag: "3.8.4av",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.8.4av - Redesign Header: Aligned with sidebar brand header, square edges across header and sidebar, page name before room breadcrumb, and relocated rooms dropdown to profile menu.",
  },
  {
    id: "3.8.4v",
    version: "3.8.4v",
    git_commit_tag: "3.8.4v",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.8.4v - Core Views UI Modernization & Notification Center Architecture: Aligned Smart Calendar, Analytics, Forecasting, and Bill Calculator with Stack Template Zinc theme; added Notification Center Activity Logs Feed with unread badges, and optimized button and avatar contrast across light and dark modes.",
  },
  {
    id: "3.8.3bv",
    version: "3.8.3bv",
    git_commit_tag: "3.8.3bv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.8.3bv - Production-Grade Settings Revamp: Re-architected settings into responsive categorized tabs (General & Tours, Household & Sharing, Notifications & Alerts, Security & Account); removed redundant appearance theme picker and developer SMTP engine diagnostics; added active user telemetry identity banner and synchronized URL search params (?tab=).",
  },
  {
    id: "3.8.3v",
    version: "3.8.3v",
    git_commit_tag: "3.8.3v",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.8.3v - Appliances Hub Modernization & Theme Alignment: Fully aligned Appliances Hub with Google Stitch / Shadcn Zinc tokens; integrated PageHeader and SectionCard architectural primitives; eliminated legacy cyan glows and gradients in favor of crisp 1px zinc borders and restrained emerald telemetry accents; streamlined toolbar controls and upgraded companion modals (Space Management, PC Workload, Inverter setup).",
  },
  {
    id: "3.8.2v",
    version: "3.8.2v",
    git_commit_tag: "3.8.2v",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.8.2v - Default Light Mode & Email Branding Overhaul: Configured Light Mode as the primary out-of-the-box default theme across AppTheme, index.html, and CSS custom properties; redesigned universal HTML email templates (Auth, SMTP diagnostics, Surge & Budget warnings) to modern light aesthetic with crisp #ffffff cards, neutral #e4e4e7 borders, and emerald accents.",
  },
  {
    id: "3.8.1v",
    version: "3.8.1v",
    git_commit_tag: "3.8.1v",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.8.1v - Full Light Mode Support: Permanent and synchronized light mode access across Desktop Sidebar, Mobile Drawer, Header, and Account Settings; persistent localStorage state with FOUC prevention in index.html; adaptive contrast tokens across all Dashboard and Admin cards.",
  },
  {
    id: "3.8.0v",
    version: "3.8.0v",
    git_commit_tag: "3.8.0v",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.8.0v - Production-grade admin design revamp: Unified Stack Template & Google Stitch zinc color system, eliminated legacy teal/glow artifacts across sidebar, header, and mobile nav, created PageHeader, SectionCard, and StatCard primitives, and restructured the dashboard into an inverted pyramid hierarchy with right rail shortcuts and full tour compatibility",
  },
  {
    id: "3.7.2cv",
    version: "3.7.2cv",
    git_commit_tag: "3.7.2cv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Developer",
    source: "github",
    description:
      "3.7.2cv - Hotfix: Add missing vite-plugin-qrcode devDependency to package.json to resolve deployment build error TS2307",
  },
  {
    id: "3.7.2bv",
    version: "3.7.2bv",
    git_commit_tag: "3.7.2bv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.7.2bv - Merge upstream v3.7.2av updates (Room-Code system, PC/Laptop Workload Mode Picker, Inverter AC stage telemetry, and persistent stopwatch storage) while preserving PR #47 design overhaul (Stack Template landing page, neutral zinc auth cards, Inter typography, and shadcn UI primitives)",
  },
  {
    id: "3.7.2av",
    version: "3.7.2av",
    git_commit_tag: "3.7.2av",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Developer",
    source: "github",
    description:
      "3.7.2av - Hotfix: Guard RoomService RPC and RoomContext room sync against unauthenticated invocations during new account registration, prevent premature active user caching on unconfirmed signups, and stamp email verification registration timestamp",
  },
  {
    id: "3.7.2v",
    version: "3.7.2v",
    git_commit_tag: "3.7.2v",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Developer",
    source: "github",
    description:
      "3.7.2v - Implement Smart 1-Tap PC & Laptop Workload Mode Picker (Idle / Office / Gaming), dynamic Inverter AC Pull-down vs Cruising stage telemetry, on-the-fly mode switching, and real-time live stopwatch cruising alerts",
  },
  {
    id: "3.7.1av",
    version: "3.7.1av",
    git_commit_tag: "3.7.1av",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Developer",
    source: "github",
    description:
      "3.7.1av - Hotfix: Resolve stopwatch and simulation plan persistence with resilient dual-write room-scoped storage, add unified SQL patch migration for simulated_appliance_usage and room member RPCs, and add smart circuit breakers to suppress repeated 42703 RPC console errors",
  },
  {
    id: "3.7.1v",
    version: "3.7.1v",
    git_commit_tag: "3.7.1v",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Developer",
    source: "github",
    description:
      "3.7.1v - Enhance UI fluidity across all resolutions (compact mobile 320px-480px, tablet 640px-1024px, and ultrawide monitors) and harmonize light mode consistency across all views, charts, and navigation components",
  },
  {
    id: "3.7.0dv",
    version: "3.7.0dv",
    git_commit_tag: "3.7.0dv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.7.0dv - Fix rapid-fire infinite fetching loop: convert Sidebar room-change synchronization into an isolated event listener to eliminate re-render cascading refetches",
  },
  {
    id: "3.7.0cv",
    version: "3.7.0cv",
    git_commit_tag: "3.7.0cv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.7.0cv - Fix room data overlap across room switching: enforce strict active room owner scoping in DataProvider, partition local fallback storage per room owner, trigger global React Query cache invalidation in switchRoom, and key layout viewports by active room ID for clean component remounts",
  },
  {
    id: "3.7.0bv",
    version: "3.7.0bv",
    git_commit_tag: "3.7.0bv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.7.0bv - Fix list_my_rooms SQL column reference from non-existent acc.name to acc.full_name, provide standalone patch migration, and implement resilient direct-table query fallback in RoomService",
  },
  {
    id: "3.7.0av",
    version: "3.7.0av",
    git_commit_tag: "3.7.0av",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.7.0av - Fix deployment build failure: restore missing JSX fragment in DashboardPage, add missing Tooltip and icon imports in PelpCatalog and Sidebar, fix DeleteOutlined import in RoomMembersPanel, and prune orphaned invite code in SettingsView",
  },
  {
    id: "3.7.0v",
    version: "3.7.0v",
    git_commit_tag: "3.7.0v",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.7.0v - Revamp Household Multi-User into Supabase Room-Code system: automatic Main Room provisioning (<<Username>>'s Room), header Room Switcher with dropdown and join code modal, Admin vs View-only role hierarchy, real-time RLS widening with loophole mitigation, and interactive members management panel",
  },
  {
    id: "3.6.0dv",
    version: "3.6.0dv",
    git_commit_tag: "3.6.0dv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.6.0dv - Excise Developer Ecosystem & OpenAPI Docs banner section from LandingPage for a streamlined, focused user interface",
  },
  {
    id: "3.6.0cv",
    version: "3.6.0cv",
    git_commit_tag: "3.6.0cv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.6.0cv - Fix Vercel build failures: migrate HouseholdAccessModal Dialog PaperProps to slotProps.paper and TextField inputProps to slotProps.input, integrate HouseholdContext addMember dispatch in SettingsView, and sanitize household storage keys upon account deletion",
  },
  {
    id: "3.6.0bv",
    version: "3.6.0bv",
    git_commit_tag: "3.6.0bv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.6.0bv - Merge upstream/main: integrate Google Gemini AI Energy Auditor with token quota preservation & intelligent fallback engine, real-time stopwatch telemetry & Live Load Circuits drawer, and Household Multi-User Access with role-based member permissions",
  },
  {
    id: "3.5.0hv",
    version: "3.5.0hv",
    git_commit_tag: "3.5.0hv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.5.0hv - Clean up Hero section on LandingPage by removing the 3 CTA action buttons and 4 trust metric badge cards, delivering a focused, distraction-free headline and subtitle presentation",
  },
  {
    id: "3.5.0gv",
    version: "3.5.0gv",
    git_commit_tag: "3.5.0gv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.5.0gv - Restore and merge all redesigned authentication views (LoginPage, SignupPage, ForgotPasswordPage, VerifyEmailPage, EmailVerifiedPage) and modal dialogs (WhatsNewModal, SystemChangelogModal, VersionBadge) with Stack Template neutral zinc design system and scoped .pf-auth theme tokens",
  },
  {
    id: "3.5.0fv",
    version: "3.5.0fv",
    git_commit_tag: "3.5.0fv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.5.0fv - Standardize full webapp typography to the Stack Template design system: Inter variable font (weights 100-900 with optical sizing & stylistic sets), JetBrains Mono for telemetry, negative heading tracking, and unified typography across Tailwind and MUI themes",
  },
  {
    id: "3.5.0ev",
    version: "3.5.0ev",
    git_commit_tag: "3.5.0ev",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.5.0ev - Apply Stack Template / shadcn neutral zinc landing page design overhaul, lightweight UI primitives (button, card, badge, separator), clean header navigation highlighting, and 100% original content preservation",
  },
  {
    id: "3.5.0dv",
    version: "3.5.0dv",
    git_commit_tag: "3.5.0dv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.5.0dv - Decommission 24-Hour Daily Load Curve Simulation from Analytics view, sync onboarding tour steps, and introduce on-demand Google Gemini AI Energy Auditor with token quota preservation, session caching, and intelligent fallback engine",
  },
  {
    id: "3.5.0cv",
    version: "3.5.0cv",
    git_commit_tag: "3.5.0cv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.5.0cv - Full 3-part synchronization across Dashboard, Appliance Hub, Sidebar, Analytics, and Forecasting: restored direct Start stopwatch button on appliance cards with live timer/spend telemetry, interactive Live Load side panel drawer with per-circuit stop controls, Today's Measured Spend KPI card on Dashboard with real-time dynamic rates, seamless Actual vs Simulated plan switching in Analytics, and interactive What-If scenario application in Forecasting",
  },
  {
    id: "3.5.0bv",
    version: "3.5.0bv",
    git_commit_tag: "3.5.0bv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.5.0bv - Complete implementation plan: Simulated Plan Quota Overrun Alert monitor, overnight push alerts on midnight rollover, plan quota settings toggle, Analytics verified actuals vs simulated history toggle, and Landing Page copy alignment",
  },
  {
    id: "3.5.0v",
    version: "3.5.0v",
    git_commit_tag: "3.5.0v",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.5.0v - Comprehensive simulation revamp: isolated simulated_appliance_usage layer from live calendar actuals, dedicated Actual Tracker vs Simulation Plan tabs, test-run stopwatch simulator, restored 24h visual stopwatch timeline with auto-logging switches, unattended stopwatch left-running alerts with midnight rollover protection, and blended predictive forecasting",
  },
  {
    id: "3.4.14cv",
    version: "3.4.14cv",
    git_commit_tag: "3.4.14cv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.4.14cv - Update system testing banner to in-memory lifecycle so it consistently reappears on page refresh (F5/Ctrl+R), logout, and restart",
  },
  {
    id: "3.4.14bv",
    version: "3.4.14bv",
    git_commit_tag: "3.4.14bv",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.4.14bv - Add HubSpot-style top testing phase announcement banner and serverless load advisory modal across app layout, landing page, and auth views",
  },
  {
    id: "3.4.14av",
    version: "3.4.14av",
    git_commit_tag: "3.4.14av",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.4.14av - Enforce single-photo scan limit (max 1 photo, 12MB raw limit) with streamlined preview UI and multi-tier payload bounding",
  },
  {
    id: "3.4.14v",
    version: "3.4.14v",
    git_commit_tag: "3.4.14v",
    created_at: "2026-10-01T07:01:08.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.4.14v - Fix AI vision scanner mobile camera uploads by introducing client-side Canvas and EXIF image compression, pre-flight payload safeguard, and enhanced serverless 413 error handling",
  },
  {
    id: "3.4.13v",
    version: "3.4.13v",
    git_commit_tag: "3.4.13v",
    created_at: "2026-10-01T06:50:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.4.13v - Comprehensive revamp of guided tour and tutorial system across all modules with head-to-toe cross-page navigation, dual-mode welcome modal, and settings management",
  },
  {
    id: "3.4.12v",
    version: "3.4.12v",
    git_commit_tag: "3.4.12v",
    created_at: new Date().toISOString(),
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.4.12v - Add interactive Web Push Setup and Troubleshooting Guide to Settings and Notification Popover for Brave, AdBlockers, and OS permissions",
  },
  {
    id: "3.4.11v",
    version: "3.4.11v",
    git_commit_tag: "3.4.11v",
    created_at: "2026-10-01T06:12:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.4.11v - Fix DevLogger Error serialization, resolve service worker readiness timing, and add diagnostic feedback for Background Web Push",
  },
  {
    id: "3.4.10v",
    version: "3.4.10v",
    git_commit_tag: "3.4.10v",
    created_at: "2026-10-01T05:55:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.4.10v - Complete Stopwatch-to-Simulation Architecture Alignment: Purge orphaned modals, harmonize Live Circuit Board, timeline load curves, extended runtime notifications, and multi-language settings",
  },
  {
    id: "3.4.9v",
    version: "3.4.9v",
    git_commit_tag: "3.4.9v",
    created_at: "2026-10-01T05:01:05.545Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.4.9v - Automated deployment and update changelog popup with intelligent commit parsing, dual-phase pre/post update triggers, and database audit sync",
  },
  {
    id: "3.4.8v",
    version: "3.4.8v",
    git_commit_tag: "3.4.8v",
    created_at: "2026-10-01T04:05:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.4.8v - Implement persistent session remember-me, intelligent root routing, and closed-app W3C Web Push notification architecture with Supabase Edge Functions",
  },
  {
    id: "3.4.7v",
    version: "3.4.7v",
    git_commit_tag: "3.4.7v",
    created_at: "2026-10-01T03:33:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.4.7v - Clean redundant emojis from UI buttons, chips, and modals, and completely remove PM Developer and Feedback to Developer modules",
  },
  {
    id: "3.4.6v",
    version: "3.4.6v",
    git_commit_tag: "3.4.6v",
    created_at: "2026-09-30T00:10:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.4.6v - Streamline Auth & Recovery: Eliminate legacy security question challenges from forgot password, registration, and account settings in favor of direct Resend SMTP email resets",
  },
  {
    id: "3.4.5v",
    version: "3.4.5v",
    git_commit_tag: "3.4.5v",
    created_at: "2026-09-29T23:20:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.4.5v - Smart Calendar Billing Period: Customizable monthly recurring billing cycles (e.g., Sept 15 to Oct 15) with cycle end day offsets (Same Day, Day Before, Day After), custom date ranges, cycle navigation, and Routine Autofill integration",
  },
  {
    id: "3.4.4v",
    version: "3.4.4v",
    git_commit_tag: "3.4.4v",
    created_at: "2026-09-29T22:45:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.4.4v - Fix Auth Session Missing: Automatically extract and initialize Supabase session from recovery tokens across single and double-hash URLs in HashRouter",
  },
  {
    id: "3.4.3v",
    version: "3.4.3v",
    git_commit_tag: "3.4.3v",
    created_at: "2026-09-29T22:30:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.4.3v - Branded HTML Email Templates: Modern PowerForecast dark theme with official logo, emerald accents, and responsive layout for Supabase Auth and transactional alerts",
  },
  {
    id: "3.4.2v",
    version: "3.4.2v",
    git_commit_tag: "3.4.2v",
    created_at: "2026-09-29T21:50:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.4.2v - Production Custom Domain SMTP: Connect verified comugallery.me domain to Resend & Supabase Auth, lifting sandbox restrictions for worldwide recipient delivery and smart energy alerts",
  },
  {
    id: "3.4.0 - BETAv",
    version: "3.4.0 - BETAv",
    git_commit_tag: "3.4.0-BETAv",
    created_at: "2026-09-28T19:53:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.4.0 - BETAv - Kickstart Simulation Architecture: Declutter Appliance Hub bento cards, remove live stopwatch power buttons and schedule queue modal, and streamline PELP quota setup",
  },
  {
    id: "3.3.8v",
    version: "3.3.8v",
    git_commit_tag: "3.3.8v",
    created_at: "2026-09-21T13:10:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.3.8v - Implement Mobile & Supabase Auth Diagnostic Suite, Service Worker auth bypass, and storage-hardened session resilience",
  },
  {
    id: "3.3.7v",
    version: "3.3.7v",
    git_commit_tag: "3.3.7v",
    created_at: "2026-09-20T12:20:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.3.7v - Implement persistent Remember Me login credentials, upgrade PWA notifications to Service Worker registration with Windows Action Center persistence, and add background notificationclick window focus handler",
  },
  {
    id: "3.3.6v",
    version: "3.3.6v",
    git_commit_tag: "3.3.6v",
    created_at: "2026-09-20T12:00:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.3.6v - Align Inverter status with category-adaptive switch (isCompressorInverterCategory), remove redundant bolt emojis across UI in favor of SVG icons, implement SemVer sorting for changelogs, and replace dynamic dates with fixed timestamps",
  },
  {
    id: "3.3.5v",
    version: "3.3.5v",
    git_commit_tag: "3.3.5v",
    created_at: "2026-09-12T14:14:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.3.5v - System-wide UI layout responsiveness & fluidity overhaul, complete dark & light mode color harmony, theme-adaptive modal papers, tooltips, dialogs, and filters",
  },
  {
    id: "3.3.4v",
    version: "3.3.4v",
    git_commit_tag: "3.3.4v",
    created_at: "2026-09-12T13:39:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.3.4v - Add appliance Blacklist toggle to exclude inactive or decommissioned devices from Smart Calendar, Forecasting calculations, and Dashboard energy metrics.",
  },
  {
    id: "3.3.3v",
    version: "3.3.3v",
    git_commit_tag: "3.3.3v",
    created_at: "2026-09-11T19:25:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.3.3v - Security hardening: remove client Gemini key config modal, revert Vite envPrefix, purge browser storage, and keep API keys 100% server-side.",
  },
  {
    id: "3.3.2v",
    version: "3.3.2v",
    git_commit_tag: "3.3.2v",
    created_at: "2026-09-10T12:00:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.3.2v - Add Inverter technology switch, live cruising telemetry, and custom running wattage override to ApplianceRoutineModal for DOE PELP additions.",
  },
  {
    id: "3.3.1v",
    version: "3.3.1v",
    git_commit_tag: "3.3.1v",
    created_at: "2026-09-09T14:30:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.3.1v - Centralize Gemini AI multi-key rotation and automated failover pool; replace Scan Mode with streamlined categories, dynamic inverter switch, and cruising telemetry; extract cruising draw via gemini-2.5-flash; add English scanning advisory notice banner; and integrate inverter telemetry into DOE PELP catalog.",
  },
  {
    id: "3.3.0v",
    version: "3.3.0v",
    git_commit_tag: "3.3.0v",
    created_at: "2026-09-08T10:00:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.3.0v - Introduce dedicated Computers & Laptops category with modular PC Hardware Spec Builder (CPU, GPU, baseline, and monitor load states), curated local JSON hardware catalog, Gemini AI fallback, and decluttered streamlined categories.",
  },
  {
    id: "3.2.6v",
    version: "3.2.6v",
    git_commit_tag: "3.2.6v",
    created_at: "2026-09-07T16:00:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.2.6v - Fix Supabase is_inverter schema cache issue: self-healing DataProvider with automatic unmigrated column recovery and migration of inverter telemetry into JSONB ai_metadata.",
  },
  {
    id: "3.2.5v",
    version: "3.2.5v",
    git_commit_tag: "3.2.5v",
    created_at: "2026-09-07T12:00:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.2.5v - Fix appliance creation modal by adding sticky action footer, enabling scrollable DialogContent with dividers, adding instant name validation feedback, and ensuring schema-safe payload handling.",
  },
  {
    id: "3.2.4v",
    version: "3.2.4v",
    git_commit_tag: "3.2.4v",
    created_at: "2026-09-07T08:00:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.2.4v - Implement Manual Cruising Wattage Input, 1/3 Duty-Cycle Calibrated Refrigeration Engine, Category-Adaptive Inverter Logic, and 7 Streamlined Everyday Appliance Categories.",
  },
  {
    id: "3.2.2v",
    version: "3.2.2v",
    git_commit_tag: "3.2.2v",
    created_at: "2026-09-06T15:00:00.000Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.2.2v - Redesign Mobile 'More' navigation drawer with right-side slide-in (anchor=right), remove redundant tabs present on mobile dock, and integrate user profile with logout, settings, live grid load telemetry, Meralco generation rate, and direct version changelogs access.",
  },
  {
    id: "3.2.1v",
    version: "3.2.1v",
    git_commit_tag: "3.2.1v",
    created_at: "2026-09-06T12:00:00Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.2.1v - Upgrade PWA App Manifest & Desktop Shell Branding: Generate native 1:1 square high-DPI icons (192x192, 512x512, and 512x512 maskable safe-zone) centered from official PowerForecast vector emblem to replace generic browser fallback on Windows Desktop, Taskbar, and Mobile PWA installations.",
  },
  {
    id: "3.2.0v",
    version: "3.2.0v",
    git_commit_tag: "3.2.0v",
    created_at: "2026-09-01T12:59:00Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.2.0v - Implement Smart Inverter Energy Engine & Dynamic Duty Cycle Calculation: Realistic compressor time-decay modeling (1st hr pull-down vs cruising mode @ ~42%), 24/7 continuous linear refrigeration factor, universal interactive fallback toggles across Manual, AI Vision Scanner, and DOE PELP modals with educational telemetry callouts.",
  },
  {
    id: "3.1.1v",
    version: "3.1.1v",
    git_commit_tag: "3.1.1v",
    created_at: "2026-09-01T07:49:00Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.1.1v - Refactor Feedback & Direct Support Modal into Developer Bento Hub featuring custom avatars with aspect-ratio preservation, exact member titles, AJ Umali quote banner, and direct Facebook Messenger PM channels for AJ Umali, Dave Villegas, and Mehojeriel Lacerna.",
  },
  {
    id: "3.1.0v",
    version: "3.1.0v",
    git_commit_tag: "3.1.0v",
    created_at: "2026-09-01T07:25:00Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.1.0v - Implement PWA automatic background update detection, Service Worker lifecycle synchronization, and interactive 'What's New & Restart to Update' popup modal with embedded live changelog notes and 1-click cache activation.",
  },
  {
    id: "3.0.4v",
    version: "3.0.4v",
    git_commit_tag: "3.0.4v",
    created_at: "2026-08-31T23:48:00Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.0.4v - Integrate Developer Direct PM channel (AJ Umali Facebook PM) and universal interactive Feedback & Support Modal across Header action bar, User profile menu, Sidebar navigation drawer, Settings view, and Landing page footer.",
  },
  {
    id: "3.0.3v",
    version: "3.0.3v",
    git_commit_tag: "3.0.3v",
    created_at: "2026-08-31T23:31:00Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.0.3v - Implement 4-Tier Smart Notification Level System (Relaxed, Standard, Proactive, Strict) with Web Audio API synthesized alert chimes, Android mobile haptic vibrations, real-time load surge spike warnings, and multi-tier budget pacing alerts.",
  },
  {
    id: "3.0.2v",
    version: "3.0.2v",
    git_commit_tag: "3.0.2v",
    created_at: "2026-08-31T22:47:00Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.0.2v - Implement inline expandable dropdown studio for appliances in Date Analytics modal on mobile viewports: selecting an appliance expands settings, quota telemetry, stopwatch sessions, and runtime controls directly underneath its card.",
  },
  {
    id: "3.0.1v",
    version: "3.0.1v",
    git_commit_tag: "3.0.1v",
    created_at: "2026-08-31T22:37:00Z",
    deployed_by: "Antigravity Pair Programmer",
    source: "github",
    description:
      "3.0.1v - Fix mobile bottom navigation label 2-line word wrapping collisions, Smart Calendar day cell price text truncation on small mobile screens, Space Switcher Bento pill bar padding and border clipping, and expand mobile layout scroll bottom clearance.",
  },
  {
    id: "3.0.0v",
    version: "3.0.0v",
    description: "3.0.0v - PowerForecast Mobile & PWA Generation: Implement Web App Manifest, Service Worker offline caching, fluid glassmorphic mobile bottom navigation dock, Android native camera capture for AI scanner, 100dvh dynamic viewport, and persistent state lifecycle reconciliation",
    git_commit_tag: "3.0.0v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-31T20:00:00.000Z",
    source: "github",
  },
  {
    id: "2.13.16v",
    version: "2.13.16v",
    description: "2.13.16v - Fix hover flickering logic on Meralco rate popover by bypassing modal backdrop interception and adding debounced mouse transition",
    git_commit_tag: "2.13.16v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-31T14:10:00.000Z",
    source: "github",
  },
  {
    id: "2.13.15v",
    version: "2.13.15v",
    description: "2.13.15v - Implement Meralco Generation Rate interactive hover breakdown popover and click-to-refetch mechanism in header",
    git_commit_tag: "2.13.15v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-30T13:55:00.000Z",
    source: "github",
  },
  {
    id: "2.13.14v",
    version: "2.13.14v",
    description: "2.13.14v - Reorder Settings layout to place Account Security & Credentials directly above the Danger Zone section",
    git_commit_tag: "2.13.14v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-30T13:45:00.000Z",
    source: "github",
  },
  {
    id: "2.13.13v",
    version: "2.13.13v",
    description: "2.13.13v - Fix Light Mode color contrasts across User Profile Menu, Sign Out dialog, GitHub Changelogs modal, and Version Badge status cards",
    git_commit_tag: "2.13.13v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-30T13:40:00.000Z",
    source: "github",
  },
  {
    id: "2.13.12v",
    version: "2.13.12v",
    description: "2.13.12v - Remove sidebar on Settings page for dedicated full-width view and add Account Security settings for password and security challenge updates",
    git_commit_tag: "2.13.12v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-30T13:30:00.000Z",
    source: "github",
  },
  {
    id: "2.13.11v",
    version: "2.13.11v",
    description: "2.13.11v - Fix auth validation, duplicate email detection, and direct security question password reset via Supabase RPC",
    git_commit_tag: "2.13.11v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-30T13:20:00.000Z",
    source: "github",
  },
  {
    id: "2.13.10v",
    version: "2.13.10v",
    description: "2.13.10v - Consolidate Manual Entry, DOE PELP Catalog, and AI Vision Scan into unified [+ Add Appliance] button with multi-tab popup window",
    git_commit_tag: "2.13.10v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-30T12:45:00.000Z",
    source: "github",
  },
  {
    id: "2.13.9v",
    version: "2.13.9v",
    description: "2.13.9v - Enhance AI vision scanner prompt with Philippine DOE yellow label standards, unit disambiguation, inverter detection, and schema parity",
    git_commit_tag: "2.13.9v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-30T12:35:00.000Z",
    source: "github",
  },
  {
    id: "2.13.8v",
    version: "2.13.8v",
    description: "2.13.8v - Revamp ApplianceRoutineModal for Light Mode with theme-adaptive dialog surfaces, white cards, high-contrast calendar grid, and emerald highlights",
    git_commit_tag: "2.13.8v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-30T12:00:00.000Z",
    source: "github",
  },
  {
    id: "2.13.1v",
    version: "2.13.1v",
    description: "2.13.1v - Overnight stopwatch 11:59 PM auto-save rollover, live multi-day timeline previews, and Option 1 smart allocation anti-duplication sync",
    git_commit_tag: "2.13.1v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-28T02:02:33.000Z",
    source: "github",
  },
  {
    id: "2.13.0v",
    version: "2.13.0v",
    description: "2.13.0v - Fix calculator, popover, auth, and component color schemes to match graphite and cyan palette",
    git_commit_tag: "2.13.0v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-27T03:03:51.000Z",
    source: "github",
  },
  {
    id: "2.12.2v",
    version: "2.12.2v",
    description: "2.12.2v - Bento corner radius harmonization across entire application, complete emoji removal, and theme aesthetics refinement",
    git_commit_tag: "2.12.2v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-27T02:44:46.000Z",
    source: "github",
  },
  {
    id: "2.12.1v",
    version: "2.12.1v",
    description: "2.12.1v - Add live stopwatch start/stop controls inside DateAnalyticsModal for Today with real-time session logging",
    git_commit_tag: "2.12.1v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-26T23:09:53.000Z",
    source: "github",
  },
  {
    id: "2.12.0v",
    version: "2.12.0v",
    description: "2.12.0v - Release 2.12.0: Appliance Target Quota system with interactive Mini Calendar historical backfill, contextual calendar telemetry, and comprehensive English & Tagalog guided tours",
    git_commit_tag: "2.12.0v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-26T23:02:09.000Z",
    source: "github",
  },
  {
    id: "2.11.1cv",
    version: "2.11.1cv",
    description: "2.11.1cv - Comprehensive system-flow aligned overhaul of guided tours across all 6 pages with pure English and Tagalog support (Taglish removed)",
    git_commit_tag: "2.11.1cv",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-26T22:59:50.000Z",
    source: "github",
  },
  {
    id: "2.11.1bv",
    version: "2.11.1bv",
    description: "2.11.1bv - Replace from-to date inputs with interactive Mini Calendar Grid date selector locked to current account month",
    git_commit_tag: "2.11.1bv",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-26T22:51:49.000Z",
    source: "github",
  },
  {
    id: "2.11.1v",
    version: "2.11.1v",
    description: "2.11.1v - Add ApplianceRoutineModal for target quotas & elaborated backfill, graceful 0h save warning, remove Use Routine Defaults toolbar button, and add interactive past timeline tracks with Progressive Routine prompt",
    git_commit_tag: "2.11.1v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-26T22:36:29.000Z",
    source: "github",
  },
  {
    id: "2.11.0bv",
    version: "2.11.0bv",
    description: "2.11.0bv - Implement Smart Date-Aware Autofill with Exclude Today toggle, decouple routine target quota from stopwatch runtime, and add date-contextual telemetry modes",
    git_commit_tag: "2.11.0bv",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-26T21:44:41.000Z",
    source: "github",
  },
  {
    id: "2.11.0v",
    version: "2.11.0v",
    description: "2.11.0v - Release PowerForecast 2.11.0 with refactored 24h activity timeline, enhanced calendar telemetry modal, and live stopwatch tracking",
    git_commit_tag: "2.11.0v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-26T21:23:39.000Z",
    source: "github",
  },
  {
    id: "2.10.7v",
    version: "2.10.7v",
    description: "2.10.7v - Refactor 24-hour activity timeline and calendar analytics modal to remove simulated routine slots, optimize live stopwatch telemetry, and streamline session inspections",
    git_commit_tag: "2.10.7v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-26T21:15:25.000Z",
    source: "github",
  },
  {
    id: "2.10.6v",
    version: "2.10.6v",
    description: "2.10.6v - Remove email verification requirement and redirect on registration to allow immediate post-signup access to dashboard",
    git_commit_tag: "2.10.6v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-26T17:43:44.000Z",
    source: "github",
  },
  {
    id: "2.10.5v",
    version: "2.10.5v",
    description: "2.10.5v - Fix calendar space filter leakage, resolve DateAnalyticsModal slider lock-in override, and include live running stopwatches in Today cell metrics",
    git_commit_tag: "2.10.5v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-26T17:14:46.000Z",
    source: "github",
  },
  {
    id: "2.10.4v",
    version: "2.10.4v",
    description: "2.10.4v - Implement registration timestamp guard, global token invalidation on auto-confirm, and database connection telemetry",
    git_commit_tag: "2.10.4v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-26T17:04:49.000Z",
    source: "github",
  },
  {
    id: "2.10.3v",
    version: "2.10.3v",
    description: "2.10.3v - Add interactive 24h timeline block inspector with edit/delete, auto-log past routines into appliance_usage_logs, and add inline editing to Schedule Queue",
    git_commit_tag: "2.10.3v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-26T16:23:20.000Z",
    source: "github",
  },
  {
    id: "2.10.2v",
    version: "2.10.2v",
    description: "2.10.2v - Fix 24-hour activity timeline calculation and visual collision bugs: enforce 24.0h daily cap, prevent duplicate manual block accounting, implement non-overlapping idle slot allocation algorithm, and refine timeline in-bar label typography",
    git_commit_tag: "2.10.2v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-26T15:52:09.000Z",
    source: "github",
  },
  {
    id: "2.10.1v",
    version: "2.10.1v",
    description: "2.10.1v - Resolve 7 calendar & daily usage logic loopholes: fix double-counting on log updates, reconcile orphaned usage on log delete, prevent passive timer drift in stopwatch edit mode, fix 24h load curve modulo collapse, prevent live session overwrite in date analytics, parse routine autofill dates at local midnight, and await bulk async deletes",
    git_commit_tag: "2.10.1v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-26T15:23:48.000Z",
    source: "github",
  },
  {
    id: "2.10.0v",
    version: "2.10.0v",
    description: "2.10.0v - Implement user registration email verification flow with cross-tab sync, optimize live power demand memoization, and add comprehensive auth documentation",
    git_commit_tag: "2.10.0v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-26T14:52:33.000Z",
    source: "github",
  },
  {
    id: "2.9.1v",
    version: "2.9.1v",
    description: "2.9.1v - Full UI Tagalog translation support and remove redundant sidebar settings link",
    git_commit_tag: "2.9.1v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-25T10:50:41.000Z",
    source: "github",
  },
  {
    id: "2.9.0v",
    version: "2.9.0v",
    description: "2.9.0v - Add dedicated Settings page, Household Sharing with invite links, strict 2-step account deletion, and sign out confirmation",
    git_commit_tag: "2.9.0v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-25T10:40:00.000Z",
    source: "github",
  },
  {
    id: "2.8.0v",
    version: "2.8.0v",
    description: "2.8.0v - Revamp Forecasting engine to be strictly data-driven based on actual logged telemetry, inventory routine baselines, and ERC unbundled calculations",
    git_commit_tag: "2.8.0v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-25T09:17:28.000Z",
    source: "github",
  },
  {
    id: "2.7.2v",
    version: "2.7.2v",
    description: "2.7.2v - Implement Master-Detail layout for daily usage log in DateAnalyticsModal",
    git_commit_tag: "2.7.2v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-25T08:49:23.000Z",
    source: "github",
  },
  {
    id: "2.7.1v",
    version: "2.7.1v",
    description: "2.7.1v - Refine multi-month trend to baseline predictions, remove weather multipliers and fake past months",
    git_commit_tag: "2.7.1v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-25T08:27:37.000Z",
    source: "github",
  },
  {
    id: "2.7.0v",
    version: "2.7.0v",
    description: "2.7.0v - Update version to 2.7.0v across system constants and package manifests",
    git_commit_tag: "2.7.0v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-25T08:19:03.000Z",
    source: "github",
  },
  {
    id: "2.6.2v",
    version: "2.6.2v",
    description: "2.6.2v - Remove hardcoded values and nonsenses on Analytics tab, add multi-space support, dynamic seasonal forecasting, and DOE PELP audit",
    git_commit_tag: "2.6.2v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-25T08:14:11.000Z",
    source: "github",
  },
  {
    id: "2.6.1cv",
    version: "2.6.1cv",
    description: "2.6.1cv - Align landing page copy with actual system capabilities, add mobile navigation drawer, and refine scrollspy boundary calculations",
    git_commit_tag: "2.6.1cv",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-24T14:02:52.000Z",
    source: "github",
  },
  {
    id: "2.6.1bv",
    version: "2.6.1bv",
    description: "2.6.1bv - Reorder landing page navigation headers to Estimator first and Platform Showcase second ([Estimator, Platform Showcase, Core Modules, Tariff Tiers, FAQ]) and update scrollspy initial state",
    git_commit_tag: "2.6.1bv",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-24T13:39:31.000Z",
    source: "github",
  },
  {
    id: "2.6.1v",
    version: "2.6.1v",
    description: "2.6.1v - Fix landing page header navigation logic with smooth scroll offsets and active scrollspy, reorder headers to Platform Showcase, Estimator, Core Modules, Tariff Tiers, FAQ, and remove API Docs link",
    git_commit_tag: "2.6.1v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-24T13:30:48.000Z",
    source: "github",
  },
  {
    id: "2.6.0v",
    version: "2.6.0v",
    description: "2.6.0v - Release major version 2.6.0 with interactive multi-language guided tour and onboarding system across Dashboard to Forecasting",
    git_commit_tag: "2.6.0v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-24T12:53:02.000Z",
    source: "github",
  },
  {
    id: "2.5.1v",
    version: "2.5.1v",
    description: "2.5.1v - Add interactive guided tour and spotlight walkthrough system across Dashboard to Forecasting with English, Tagalog, and Taglish language support",
    git_commit_tag: "2.5.1v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-24T12:46:16.000Z",
    source: "github",
  },
  {
    id: "2.1.5v",
    version: "2.1.5v",
    description: "2.1.5v - Fix missing useNavigate hook in LandingPage to resolve Vercel build failure",
    git_commit_tag: "2.1.5v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-22T14:46:29.000Z",
    source: "github",
  },
  {
    id: "2.1.4v",
    version: "2.1.4v",
    description: "2.1.4v - Fix TS2304 build error by removing unused useLogin and useNavigate references in LandingPage",
    git_commit_tag: "2.1.4v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-22T14:41:30.000Z",
    source: "github",
  },
  {
    id: "2.1.3v",
    version: "2.1.3v",
    description: "2.1.3v - Enforce strict Supabase authentication validation, eliminate login bypasses, and add Authenticated route guards",
    git_commit_tag: "2.1.3v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-22T14:36:55.000Z",
    source: "github",
  },
  {
    id: "2.1.2v",
    version: "2.1.2v",
    description: "2.1.2v - Fix blank screen on Vercel by migrating vercel.json routes to rewrites and setting Vite base path to /",
    git_commit_tag: "2.1.2v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-22T14:25:57.000Z",
    source: "github",
  },
  {
    id: "2.1.1v",
    version: "2.1.1v",
    description: "2.1.1v - Integrate energy calculation & accuracy solutions document, live tracking optimizations, and push to PowerForecast-2v repository",
    git_commit_tag: "2.1.1v",
    deployed_by: "hAizen-Nibba",
    created_at: "2026-08-22T14:20:22.000Z",
    source: "github",
  },
];
